--(1)유저 생성 전 확인 사항

SELECT * 
FROM DBA_USERS
ORDER BY ACCOUNT_STATUS DESC, USERNAME;

--
SELECT * 
FROM DBA_DATA_FILES;

--권한확인
SELECT * FROM DBA_SYS_PRIVS;


SELECT DISTINCT PRIVILEGE
FROM DBA_SYS_PRIVS
ORDER BY 1;

SELECT * FROM DBA_ROLES;

SELECT * FROM
DBA_PROFILES
ORDER BY profile, RESOURCE_TYPE;

--
SET SERVEROUTPUT ON;


--(2)필요시 테이블 스페이스 생성
SELECT NAME FROM V$DATAFILE;
CREATE TABLESPACE MYTBS
DATAFILE 'C:\APP\KOSA\PRODUCT\21C\ORADATA\XE\XEPDB1\MYTBS01.DBF' SIZE 100M;


/*
DECLARE 
V_PATH VARCHAR2(100); 
BEGIN
SELECT SUBSTR(NAME, 1, INSTR(NAME, '\', -1) ) AS PATH
INTO V_PATH
FROM V$DATAFILE
WHERE NAME LIKE '%SYSTEM01%';
DBMS_OUTPUT.PUT_LINE(V_PATH);
EXECUTE IMMEDIATE 'CREATE TABLESPACE MYTBS DATAFILE'''||V_PATH||'MYTBS01.DBF'' SIZE 100M';
END;
/
*/


--(3)필요시 ROLE 생성
DROP ROLE DEV_ROLE;
CREATE ROLE DEV_ROLE;
GRANT CREATE SESSION, CREATE TABLE 
TO DEV_ROLE;

--ACE01 의 EMP 테이블의 SELECT 권한을 DEV_ROLE에 부여
GRANT SELECT 
ON ACE01.EMP
TO DEV_ROLE;

-- (4)필요시 PROFILE 생성
CREATE PROFILE DEV_PROFILE LIMIT
FAILED_LOGIN_ATTEMPTS 3
SESSIONS_PER_USER 3;
-- 사용자가 동시에 생성할 수 있는 세션(session)의 최대 수를 제한

/*

  FAILED_LOGIN_ATTEMPTS 5
   PASSWORD_LIFE_TIME 60
   PASSWORD_REUSE_TIME 60
   PASSWORD_REUSE_MAX 5
   PASSWORD_VERIFY_FUNCTION ora12c_verify_function
   PASSWORD_LOCK_TIME 1/24
   PASSWORD_GRACE_TIME 10
   INACTIVE_ACCOUNT_TIME 30;
*/
-- (5)USER 생성
    CREATE USER TIME
    IDENTIFIED BY INOUT
    DEFAULT TABLESPACE USERS
    QUOTA 5M ON USERS
    QUOTA UNLIMITED ON MYTBS
    PROFILE DEV_PROFILE
    PASSWORD EXPIRE;
    
    GRANT DEV_ROLE
    TO TIME, ACE02, ACE03;

-- 객체 생성
/*
SQLPLUS에서 접속
TIME/INOUT@LOCALHOST:1521/XEPDB1

SHOW USER ;
CREATE TABLE T1 (NO NUMBER);
INSERT INTO T1 VALUES(1000);
INSERT INTO T1 VALUES(2000);
COMMIT;
*/
-- 다른 유저에게 객체 생성 권한 부여



    
--(6) 다른 유저에게 권한 부여\
-- TIME 계정에서 접속
GRANT SELECT, INSERT 
ON T1 
TO ACE03;


SELECT * FROM TAB;

-- 참고
/*

*/
    

--(7)ACE02 유저로 접속해서 다른 유저의 객체 사용


select * from dba_rollback_segs;










