SET SERVEROUTPUT ON;


-- 묵시적 커서 예제
BEGIN
	UPDATE DEPT SET DNAME='DATABASE'
	WHERE DEPTNO = 50;
DBMS_OUTPUT.PUT_LINE('갱신된 LINE 수 : '||SQL%ROWCOUNT);
IF(SQL%FOUND) THEN DBMS_OUTPUT.PUT_LINE('행 존재 여부 : TRUE');
ELSE DBMS_OUTPUT.PUT_LINE('행 존재 여부 : FALSE');
END IF;

IF(SQL%ISOPEN) THEN 
DBMS_OUTPUT.PUT_LINE('커서의 상태 : OPEN');
ELSE DBMS_OUTPUT.PUT_LINE('커서의 상태 : CLOSE');
END IF;

END;
/

--DECLARE 생략(묵시적 커서)
BEGIN 
    UPDATE DEPT SET DNAME='DATABASE'
    WHERE DEPTNO=50; -- 50번 부서는 존재하지 않음
    DBMS_OUTPUT.PUT_LINE('갱신된 LINE 수 : '||SQL%ROWCOUNT);
    IF(SQL%NOTFOUND)THEN DBMS_OUTPUT.PUT_LINE('결과를 찾지 못했습니다.');
    ELSE DBMS_OUTPUT.PUT_LINE('결과를 찾았습니다!');
    END IF;
    IF(SQL%ISOPEN) THEN DBMS_OUTPUT.PUT_LINE('커서가 열려 있습니다!');
    ELSE DBMS_OUTPUT.PUT_LINE('커서가 닫혀 있습니다.');
    END IF;
END;
/


SELECT * FROM DEPT;

DECLARE 
TYPE REC1 IS RECORD(DNUM DEPT.DEPTNO%TYPE, DNAME DEPT.DNAME%TYPE, DLOC DEPT.LOC%TYPE);
R1 REC1;
BEGIN 
SELECT D.DEPTNO, D.DNAME, D.LOC INTO R1.DNUM, R1.DNAME, R1.DLOC
FROM DEPT D
WHERE D.DEPTNO = 10;

DBMS_OUTPUT.PUT_LINE('부서 번호 : '||R1.DNUM);
END;
/

DECLARE 
TYPE REC1 IS RECORD(DROW DEPT%ROWTYPE);
R1 REC1;
BEGIN
SELECT * INTO R1.DROW
FROM DEPT 
WHERE DEPTNO=10;
END;
/