SELECT * FROM EMP;

SET SERVEROUTPUT ON;

-- CASE 01

CREATE OR REPLACE PROCEDURE PRO1 (P_EMPNO EMP.EMPNO%TYPE) 
IS
V_SAL EMP.SAL%TYPE;
BEGIN 
SELECT SAL INTO V_SAL
FROM EMP
WHERE EMPNO = P_EMPNO;
DBMS_OUTPUT.PUT_LINE('급여 : '||V_SAL);
END;
/

EXEC PRO1(7788);

SELECT * FROM EMP;

CREATE OR REPLACE PROCEDURE PRO1(P_EMPNO EMP.EMPNO%TYPE) 
IS
V_ENAME EMP.ENAME%TYPE;
V_JOB EMP.JOB%TYPE;
V_SAL EMP.SAL%TYPE;
V_DEPTNO EMP.DEPTNO%TYPE;
BEGIN 
SELECT ENAME, JOB, SAL, DEPTNO
INTO V_ENAME, V_JOB, V_SAL, V_DEPTNO
FROM EMP
WHERE EMPNO = P_EMPNO;
DBMS_OUTPUT.PUT_LINE('사번 : '||P_EMPNO||', 이름 : '||V_ENAME||
', 직업 : '||V_JOB||', 급여 : '||V_SAL||', 부서 번호 : '||V_DEPTNO);
END;
/

EXEC PRO1(7788);


-- CASE 02
CREATE OR REPLACE PROCEDURE PRO2(P_EMPNO EMP.EMPNO%TYPE) 
IS
REC_EMP EMP%ROWTYPE;
BEGIN 
SELECT * INTO REC_EMP
FROM EMP
WHERE EMPNO = P_EMPNO; 
DBMS_OUTPUT.PUT_LINE(REC_EMP.ENAME);
DBMS_OUTPUT.PUT_LINE(REC_EMP.SAL);
DBMS_OUTPUT.PUT_LINE(REC_EMP.ENAME||', '||REC_EMP.SAL);
END;
/

EXEC PRO2(7788);


CREATE OR REPLACE PROCEDURE PRO2(P_EMPNO EMP.EMPNO%TYPE) 
IS
TYPE REC_EMP IS RECORD(
V_ENAME EMP.ENAME%TYPE,
V_SAL   EMP.SAL%TYPE,
V_DEPTNO EMP.DEPTNO%TYPE
);
REC REC_EMP;
BEGIN 
SELECT ENAME, SAL, DEPTNO 
INTO REC.V_ENAME, REC.V_SAL, REC.V_DEPTNO
FROM EMP
WHERE EMPNO = P_EMPNO;
DBMS_OUTPUT.PUT_LINE('이름 : '||REC.V_ENAME||', 급여 : '||REC.V_SAL||
', 부서번호 : '||REC.V_DEPTNO);
END;
/


EXEC PRO2(7788);

--STEP03(커스텀레코드)
CREATE OR REPLACE PROCEDURE PRO3 (P_EMPNO EMP.EMPNO%TYPE)
IS
TYPE REC IS RECORD(
ENAME EMP.ENAME%TYPE,
SAL EMP.SAL%TYPE,
JOB EMP.JOB%TYPE
);
REC_EMP REC;
BEGIN
SELECT ENAME, SAL, JOB 
INTO REC_EMP.ENAME, REC_EMP.SAL, REC_EMP.JOB 
FROM EMP
WHERE EMPNO = P_EMPNO;
DBMS_OUTPUT.PUT_LINE('이름 : '||REC_EMP.ENAME||', 급여 : '||REC_EMP.SAL||', 직업 : '||REC_EMP.JOB);
END;
/

EXEC PRO3(7788);

--STEP03(패키지)
CREATE OR REPLACE PACKAGE REC_EMP_PACK
IS
TYPE REC IS RECORD(
ENAME EMP.ENAME%TYPE,
SAL EMP.SAL%TYPE,
JOB EMP.JOB%TYPE
);
END;
/
CREATE OR REPLACE PROCEDURE PRO3 (P_EMPNO EMP.EMPNO%TYPE)
IS
REC_EMP REC_EMP_PACK.REC;
BEGIN 
SELECT ENAME, SAL, JOB 
INTO REC_EMP.ENAME, REC_EMP.SAL, REC_EMP.JOB 
FROM EMP
WHERE EMPNO = P_EMPNO;
DBMS_OUTPUT.PUT_LINE('이름 : '||REC_EMP.ENAME||', 급여 : '||REC_EMP.SAL||', 직업 : '||REC_EMP.JOB);
END;
/

EXEC PRO3(7788);

--SETP03(VIEW)
CREATE OR REPLACE VIEW V1
AS
SELECT ENAME, SAL, JOB 
FROM EMP;
/
CREATE OR REPLACE PROCEDURE PRO3(P_EMPNO EMP.EMPNO%TYPE)
IS 
REC_EMP V1%ROWTYPE;
BEGIN 
SELECT ENAME, SAL, JOB 
INTO REC_EMP.ENAME, REC_EMP.SAL, REC_EMP.JOB 
FROM EMP
WHERE EMPNO = P_EMPNO;
DBMS_OUTPUT.PUT_LINE('이름 : '||REC_EMP.ENAME||', 급여 : '||REC_EMP.SAL||', 직업 : '||REC_EMP.JOB);
END;
/

EXEC PRO3(7788);


--MY03 커스텀레코드
SELECT * FROM EMPLOYEES;
CREATE OR REPLACE PROCEDURE PRO3(P_EMPLOYEE_ID EMPLOYEES.EMPLOYEE_ID%TYPE)
IS
TYPE REC IS RECORD(
FIRST_NAME EMPLOYEES.FIRST_NAME%TYPE,
LAST_NAME EMPLOYEES.LAST_NAME%TYPE,
EMAIL EMPLOYEES.EMAIL%TYPE,
SALARY EMPLOYEES.SALARY%TYPE
);
REC_EMP REC;
BEGIN
SELECT FIRST_NAME, LAST_NAME, EMAIL, SALARY 
INTO REC_EMP.FIRST_NAME, REC_EMP.LAST_NAME, REC_EMP.EMAIL, REC_EMP.SALARY
FROM EMPLOYEES
WHERE EMPLOYEE_ID = P_EMPLOYEE_ID;
DBMS_OUTPUT.PUT_LINE('이름 : '||REC_EMP.FIRST_NAME||' '||REC_EMP.LAST_NAME||', 이메일 : '||REC_EMP.EMAIL||', 급여 : '||REC_EMP.SALARY);
END;
/
EXEC PRO3(149);

--MY03 패키지
CREATE OR REPLACE PACKAGE EMPLOYEES_PACK 
IS
TYPE REC IS RECORD(
FIRST_NAME EMPLOYEES.FIRST_NAME%TYPE,
LAST_NAME EMPLOYEES.LAST_NAME%TYPE,
EMAIL EMPLOYEES.EMAIL%TYPE,
SALARY EMPLOYEES.SALARY%TYPE
);
END;
/
CREATE OR REPLACE PROCEDURE PRO3(P_EMPLOYEE_ID EMPLOYEES.EMPLOYEE_ID%TYPE)
IS
REC_EMP EMPLOYEES_PACK.REC;
BEGIN
SELECT FIRST_NAME, LAST_NAME, EMAIL, SALARY 
INTO REC_EMP.FIRST_NAME, REC_EMP.LAST_NAME, REC_EMP.EMAIL, REC_EMP.SALARY
FROM EMPLOYEES
WHERE EMPLOYEE_ID = P_EMPLOYEE_ID;
DBMS_OUTPUT.PUT_LINE('이름 : '||REC_EMP.FIRST_NAME||' '||REC_EMP.LAST_NAME||', 이메일 : '||REC_EMP.EMAIL||', 급여 : '||REC_EMP.SALARY);
END;
/
EXEC PRO3(149);

--MY03 VIEW 활용
CREATE OR REPLACE VIEW V1 
AS
SELECT FIRST_NAME, LAST_NAME, EMAIL, SALARY 
FROM EMPLOYEES;
/
CREATE OR REPLACE PROCEDURE PRO3(P_EMPLOYEE_ID EMPLOYEES.EMPLOYEE_ID%TYPE)
IS
REC_EMP V1%ROWTYPE;
BEGIN
SELECT FIRST_NAME, LAST_NAME, EMAIL, SALARY 
INTO REC_EMP.FIRST_NAME, REC_EMP.LAST_NAME, REC_EMP.EMAIL, REC_EMP.SALARY
FROM EMPLOYEES
WHERE EMPLOYEE_ID = P_EMPLOYEE_ID;
DBMS_OUTPUT.PUT_LINE('이름 : '||REC_EMP.FIRST_NAME||' '||REC_EMP.LAST_NAME||', 이메일 : '||REC_EMP.EMAIL||', 급여 : '||REC_EMP.SALARY);
END;
/
EXEC PRO3(149);


--STEP04 
CREATE OR REPLACE PROCEDURE PRO4(P_DEPTNO EMP.DEPTNO%TYPE)
IS
TYPE TAB1 IS TABLE OF EMP.SAL%TYPE
INDEX BY PLS_INTEGER;
EMP_TAB TAB1;
BEGIN 
SELECT SAL BULK COLLECT INTO EMP_TAB
FROM EMP
WHERE DEPTNO = P_DEPTNO;
DBMS_OUTPUT.PUT_LINE(EMP_TAB.FIRST);
DBMS_OUTPUT.PUT_LINE(EMP_TAB.LAST);
FOR I IN EMP_TAB.FIRST .. EMP_TAB.LAST LOOP
DBMS_OUTPUT.PUT_LINE(EMP_TAB(I));
END LOOP;
END;
/
EXEC PRO4(20);





SELECT * FROM EMP;

CREATE OR REPLACE PROCEDURE PRO4 (P_DEPTNO EMP.DEPTNO%TYPE) 
IS
TYPE TAB1 IS TABLE OF EMP%ROWTYPE
INDEX BY PLS_INTEGER;
EMP_TAB TAB1;
BEGIN 
SELECT * BULK COLLECT INTO EMP_TAB
FROM EMP
WHERE DEPTNO = P_DEPTNO;
DBMS_OUTPUT.PUT_LINE(EMP_TAB.FIRST);
DBMS_OUTPUT.PUT_LINE(EMP_TAB.LAST);
FOR I IN EMP_TAB.FIRST .. EMP_TAB.LAST LOOP
DBMS_OUTPUT.PUT_LINE('사번 : '||EMP_TAB(I).EMPNO||', 이름 : '||EMP_TAB(I).ENAME||', 급여 : '||EMP_TAB(I).SAL);
END LOOP;
END;
/

EXEC PRO4(20);

--STEP05
CREATE OR REPLACE PROCEDURE PRO5(P_DEPTNO EMP.DEPTNO%TYPE) 
IS 
TYPE TAB1 IS TABLE OF EMP%ROWTYPE
INDEX BY PLS_INTEGER;
EMP_TAB TAB1;
BEGIN 
SELECT * BULK COLLECT INTO EMP_TAB 
FROM EMP
WHERE DEPTNO = P_DEPTNO; 
DBMS_OUTPUT.PUT_LINE(EMP_TAB.LAST);
FOR I IN EMP_TAB.FIRST .. EMP_TAB.LAST LOOP
DBMS_OUTPUT.PUT_LINE(EMP_TAB(I).EMPNO||' : '||EMP_TAB(I).ENAME);
END LOOP;
END;
/
EXEC PRO5(20);


CREATE OR REPLACE PACKAGE EMP_PACK IS
TYPE TAB1 IS TABLE OF EMP%ROWTYPE 
INDEX BY PLS_INTEGER;
END;
/
CREATE OR REPLACE PROCEDURE PRO5(P_DEPTNO EMP.DEPTNO%TYPE)
IS 
EMP_TAB EMP_PACK.TAB1;
BEGIN 
SELECT * BULK COLLECT INTO EMP_TAB 
FROM EMP
WHERE DEPTNO = P_DEPTNO; 
DBMS_OUTPUT.PUT_LINE(EMP_TAB.LAST);
FOR I IN EMP_TAB.FIRST .. EMP_TAB.LAST LOOP
DBMS_OUTPUT.PUT_LINE(EMP_TAB(I).EMPNO||' : '||EMP_TAB(I).ENAME);
END LOOP;
END;
/
EXEC PRO5(20);

--STEOP06
CREATE OR REPLACE PROCEDURE PROC1(P_DEPTNO EMP.DEPTNO%TYPE)
IS
TYPE EMP_RECORD_TYPE IS RECORD
(EMPNO EMP.EMPNO%TYPE,
ENAME EMP.ENAME%TYPE,
SAL   EMP.SAL%TYPE,
JOB   EMP.JOB%TYPE);

TYPE EMP_TABLE_TYPE IS TABLE OF EMP_RECORD_TYPE
INDEX BY PLS_INTEGER;

EMP_TAB EMP_TABLE_TYPE;
BEGIN
SELECT EMPNO, ENAME, SAL, JOB BULK COLLECT INTO EMP_TAB
FROM EMP
WHERE DEPTNO = P_DEPTNO;

FOR I IN EMP_TAB.FIRST .. EMP_TAB.LAST LOOP
DBMS_OUTPUT.PUT_LINE(EMP_TAB(I).EMPNO);
DBMS_OUTPUT.PUT_LINE(EMP_TAB(I).ENAME);
DBMS_OUTPUT.PUT_LINE('-----');
END LOOP;
END;
/
EXEC PROC1(20);

  EXEC PROC1(20)



CREATE OR REPLACE PROCEDURE PRO6(P_DEPTNO EMP.DEPTNO%TYPE) 
IS
TYPE REC IS RECORD(
EMPNO EMP.EMPNO%TYPE,
ENAME EMP.ENAME%TYPE,
SAL EMP.SAL%TYPE
);

TYPE TAB1 IS TABLE OF REC
INDEX BY PLS_INTEGER;

REC_TAB TAB1;

BEGIN 

SELECT EMPNO, ENAME, SAL BULK COLLECT INTO REC_TAB
FROM EMP
WHERE DEPTNO = P_DEPTNO;

DBMS_OUTPUT.PUT_LINE(REC_TAB.LAST);
FOR I IN REC_TAB.FIRST .. REC_TAB.LAST LOOP
DBMS_OUTPUT.PUT_LINE('사번 : '||REC_TAB(I).EMPNO||', 이름 : '||REC_TAB(I).ENAME||', 급여 : '||REC_TAB(I).SAL);
END LOOP;
END;
/
EXEC PRO6(20);





CREATE OR REPLACE PROCEDURE PRO6(P_DEPTNO EMP.DEPTNO%TYPE) 
IS
TYPE REC IS RECORD(
EMPNO EMP.EMPNO%TYPE,
ENAME EMP.ENAME%TYPE,
SAL EMP.SAL%TYPE
);

TYPE TAB1 IS TABLE OF REC 
INDEX BY PLS_INTEGER;
REC_TAB TAB1;

BEGIN

SELECT EMPNO, ENAME, SAL BULK COLLECT INTO REC_TAB
FROM EMP
WHERE DEPTNO = P_DEPTNO;

DBMS_OUTPUT.PUT_LINE(REC_TAB.LAST);
FOR I IN REC_TAB.FIRST .. REC_TAB.LAST LOOP
DBMS_OUTPUT.PUT_LINE('사번 : '||REC_TAB(I).EMPNO||', 이름 : '||REC_TAB(I).ENAME||', 급여 : '||REC_TAB(I).SAL);
END LOOP;
END;
/

EXEC PRO6(20);
