DROP TABLE T1 PURGE;

CREATE TABLE T1(NO NUMBER);
SELECT * FROM TAB;
DESC T1;

select * from tab;

purge RECYCLEBIN;

SET SERVEROUTPUT ON; -- 하기 전까지 출력이 안됨!
BEGIN
    DBMS_OUTPUT.PUT_LINE('HELLO PL/SQL');
END;
/

DECLARE -- 선언부
V_EMPNO NUMBER(4) := 7788; -- 변수명 : V_EMPNO, 타입 : NUMBER(길이) = 7788;
V_ENAME VARCHAR2(10); -- 변수명 : V_ENAME, 타입 : VARCHAR2(길이);
/*
VARCHAR 와 VARCHAR2 의 차이가 뭐지? 
-> 현재는 완전 동일한 기능이지만 VARCHAR2 사용 강력권장!!!!  
WHY? -> VARCHAR 데이터 타입은 추후 ORACLE이 변경 예정이라함 
*/
BEGIN -- 실행부
    V_ENAME := 'SCOTT'; -- V_NAME, 타입 : VARCHAR2(10) = 'SCOTT'
    -- DBMS_OUTPUT.PUT_LINE('V_EMPNO: '|| V_EMPNO);
    DBMS_OUTPUT.PUT_LINE('V_ENAME: '|| V_ENAME);
END;
/
/*
결과 예상 : 선언부(DECLARE)에서 선언한 변수를 실행부(BEGIN) 에서 
        DBMS_OUTPUT.PUT_LINE() 으로 출력하는 구조
        V_EMPNO = 7788, V_ENAME = SCOTT(실행부에 지정)
        주석처리된 V_EMPNO 는 출력되지 않고 SCOTT만 출력될듯?
*/

DECLARE 
    V_EMPNO NUMBER(4) := 4885;
    V_ENAME VARCHAR2(10);
BEGIN
    V_ENAME := 'SMART';
    DBMS_OUTPUT.PUT_LINE('V_EMPNO : '||V_EMPNO);
    DBMS_OUTPUT.PUT_LINE('V_ENAME : '||V_ENAME);
END;
/

DECLARE 
    V_TAX CONSTANT NUMBER(1) := 3;
BEGIN
    DBMS_OUTPUT.PUT_LINE('V_TAX : '||V_TAX);
END;
/

DECLARE
    V_DEPTNO NUMBER(2) DEFAULT 10;
BEGIN 
    DBMS_OUTPUT.PUT_LINE('V_DEPTNO : '||V_DEPTNO);
END;
/

DECLARE 
    V_DEPNO NUMBER(2) NOT NULL DEFAULT 10;
BEGIN
    DBMS_OUTPUT.PUT_LINE('V_DEPNO : '||V_DEPNO);
END;
/
-- 이거 := 랑 DEFAULT 랑 똑같은거 아냐? 
-- 맞네..

DECLARE 
    V_DEPTNO DEPT.DEPTNO%TYPE := 50;
BEGIN
    DBMS_OUTPUT.PUT_LINE('V_DEPTNO : '||V_DEPTNO);
END;
/
SELECT * FROM DEPT;

DECLARE
    V_DEPT_ROW DEPT%ROWTYPE;
BEGIN
    SELECT DEPTNO, DNAME, LOC INTO V_DEPT_ROW 
    FROM DEPT
    WHERE DEPTNO = 40;
    DBMS_OUTPUT.PUT_LINE('DEPTNO : '||V_DEPT_ROW.DEPTNO);
    DBMS_OUTPUT.PUT_LINE('DNAME : '||V_DEPT_ROW.DNAME);
    DBMS_OUTPUT.PUT_LINE('LOC : '||V_DEPT_ROW.LOC);
END;
/
SHOW ERRORS;